[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "million-trader-signals"
version = "1.0.0"
description = "Trading signals and analysis modules for Million Trader"
authors = [
    {name = "Million Trader Team", email = "team@milliontrader.io"}
]
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.1.0",
    "numpy>=1.24.0",
    "pandas-ta>=0.3.14b0",
    "scikit-learn>=1.3.0",
    "lightgbm>=4.1.0",
    "scipy>=1.11.0",
    "loguru>=0.7.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.7.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["signals*"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"

